name: Quality Assurance
on: [ push, pull_request ]

jobs:
  QA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install shellcheck v0.9.0
        run: ./lib/tegonal-scripts/src/ci/install-shellcheck.sh
      - name: run before-pr
        run: ./scripts/before-pr.sh
