name: "Scripts Code Quality"
on: [push, pull_request]

jobs:
  CodeQuality:
    name: Scripts Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          ignore: lib/tegonal-scripts
        env:
          SHELLCHECK_OPTS: -C -x -o all -P ./scripts:./lib/tegonal-scripts/src
